export interface PermissionDef {
  resource: string
  action: string
  scope: string
  description: string
}

export interface RoleDef {
  key: string
  displayNameAr: string
  displayNameEn: string
  description: string
  permissionKeys: string[]
}

export const PERMISSIONS: PermissionDef[] = [
  {
    resource: 'billing',
    action: 'manage',
    scope: '',
    description: 'Manage billing and subscriptions',
  },
  {
    resource: 'company_settings',
    action: 'manage',
    scope: '',
    description: 'Manage company settings',
  },
  { resource: 'company_settings', action: 'read', scope: '', description: 'View company settings' },
  {
    resource: 'employees',
    action: 'manage',
    scope: '',
    description: 'Full employee management (CRUD)',
  },
  { resource: 'employees', action: 'read', scope: '', description: 'View all employee details' },
  {
    resource: 'employees',
    action: 'read_basic',
    scope: '',
    description: 'View employee names only',
  },
  {
    resource: 'attendance',
    action: 'manage',
    scope: '',
    description: 'Manage all attendance records',
  },
  { resource: 'attendance', action: 'read_team', scope: '', description: 'View team attendance' },
  { resource: 'attendance', action: 'read_own', scope: '', description: 'View own attendance' },
  { resource: 'payroll', action: 'manage', scope: '', description: 'Manage payroll' },
  { resource: 'crm_leads', action: 'manage', scope: '', description: 'Manage leads pipeline' },
  { resource: 'clients', action: 'manage', scope: '', description: 'Manage clients' },
  { resource: 'clients', action: 'read', scope: '', description: 'View clients' },
  { resource: 'clients', action: 'read_self', scope: '', description: 'View own client profile' },
  { resource: 'projects', action: 'manage', scope: '', description: 'Manage all projects' },
  {
    resource: 'projects',
    action: 'read_assigned',
    scope: '',
    description: 'View assigned projects',
  },
  { resource: 'projects', action: 'read_own', scope: '', description: 'View own projects' },
  { resource: 'tasks', action: 'manage', scope: '', description: 'Manage all tasks' },
  { resource: 'tasks', action: 'read_assigned', scope: '', description: 'View assigned tasks' },
  { resource: 'asset_library', action: 'manage', scope: '', description: 'Manage asset library' },
  {
    resource: 'asset_library',
    action: 'read_assigned',
    scope: '',
    description: 'View assigned assets',
  },
  {
    resource: 'content_calendar',
    action: 'manage',
    scope: '',
    description: 'Manage content calendar',
  },
  { resource: 'content_calendar', action: 'read_own', scope: '', description: 'View own content' },
  { resource: 'ai_tools', action: 'access', scope: '', description: 'Access AI creative tools' },
  { resource: 'equipment', action: 'manage', scope: '', description: 'Manage equipment' },
  { resource: 'exhibitions', action: 'manage', scope: '', description: 'Manage exhibitions' },
  {
    resource: 'quotations_invoices',
    action: 'manage',
    scope: '',
    description: 'Manage quotations and invoices',
  },
  {
    resource: 'quotations_invoices',
    action: 'view',
    scope: '',
    description: 'View quotations and invoices',
  },
  {
    resource: 'quotations_invoices',
    action: 'read_own',
    scope: '',
    description: 'View own invoices',
  },
  { resource: 'expenses', action: 'manage', scope: '', description: 'Manage all expenses' },
  { resource: 'expenses', action: 'submit', scope: '', description: 'Submit expenses' },
  { resource: 'reports', action: 'manage', scope: '', description: 'View all reports' },
  { resource: 'reports', action: 'read_hr', scope: '', description: 'View HR reports only' },
  { resource: 'reports', action: 'read_own', scope: '', description: 'View own reports' },
  { resource: 'audit_logs', action: 'manage', scope: '', description: 'View audit logs' },
]

export function permissionKey(p: { resource: string; action: string; scope: string }): string {
  return p.scope ? `${p.resource}.${p.action}.${p.scope}` : `${p.resource}.${p.action}`
}

export const ROLES: RoleDef[] = [
  {
    key: 'owner',
    displayNameAr: 'مالك',
    displayNameEn: 'Owner',
    description: 'Full access to all features including billing',
    permissionKeys: [
      'billing.manage',
      'company_settings.manage',
      'employees.manage',
      'attendance.manage',
      'payroll.manage',
      'crm_leads.manage',
      'clients.manage',
      'projects.manage',
      'tasks.manage',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'equipment.manage',
      'exhibitions.manage',
      'quotations_invoices.manage',
      'expenses.manage',
      'reports.manage',
      'audit_logs.manage',
    ],
  },
  {
    key: 'admin',
    displayNameAr: 'مدير',
    displayNameEn: 'Admin',
    description: 'Full access except billing',
    permissionKeys: [
      'company_settings.manage',
      'employees.manage',
      'attendance.manage',
      'payroll.manage',
      'crm_leads.manage',
      'clients.manage',
      'projects.manage',
      'tasks.manage',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'equipment.manage',
      'exhibitions.manage',
      'quotations_invoices.manage',
      'expenses.manage',
      'reports.manage',
      'audit_logs.manage',
    ],
  },
  {
    key: 'hr_manager',
    displayNameAr: 'مدير موارد بشرية',
    displayNameEn: 'HR Manager',
    description: 'HR and employee management',
    permissionKeys: [
      'company_settings.read',
      'employees.manage',
      'attendance.manage',
      'payroll.manage',
      'expenses.submit',
      'reports.read_hr',
    ],
  },
  {
    key: 'project_manager',
    displayNameAr: 'مدير مشاريع',
    displayNameEn: 'Project Manager',
    description: 'Manage projects, tasks, and client communication',
    permissionKeys: [
      'company_settings.read',
      'employees.read_basic',
      'attendance.read_team',
      'clients.read',
      'projects.manage',
      'tasks.manage',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'equipment.manage',
      'exhibitions.manage',
      'quotations_invoices.view',
      'expenses.submit',
      'reports.read_own',
    ],
  },
  {
    key: 'creative_director',
    displayNameAr: 'مدير إبداعي',
    displayNameEn: 'Creative Director',
    description: 'Oversee creative output across projects',
    permissionKeys: [
      'company_settings.read',
      'employees.read_basic',
      'attendance.read_team',
      'clients.read',
      'projects.manage',
      'tasks.manage',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'equipment.manage',
      'exhibitions.manage',
      'expenses.submit',
      'reports.read_own',
    ],
  },
  {
    key: 'designer',
    displayNameAr: 'مصمم',
    displayNameEn: 'Designer',
    description: 'Create designs and manage creative assets',
    permissionKeys: [
      'employees.read_basic',
      'attendance.read_own',
      'projects.read_assigned',
      'tasks.read_assigned',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'equipment.manage',
      'expenses.submit',
    ],
  },
  {
    key: 'video_editor',
    displayNameAr: 'محرر فيديو',
    displayNameEn: 'Video Editor',
    description: 'Edit videos and manage media assets',
    permissionKeys: [
      'employees.read_basic',
      'attendance.read_own',
      'projects.read_assigned',
      'tasks.read_assigned',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'equipment.manage',
      'expenses.submit',
    ],
  },
  {
    key: 'account_manager',
    displayNameAr: 'مدير حسابات',
    displayNameEn: 'Account Manager',
    description: 'Manage client accounts, leads, and projects',
    permissionKeys: [
      'employees.read_basic',
      'attendance.read_own',
      'crm_leads.manage',
      'clients.manage',
      'projects.manage',
      'tasks.manage',
      'asset_library.manage',
      'content_calendar.manage',
      'ai_tools.access',
      'exhibitions.manage',
      'quotations_invoices.manage',
      'expenses.submit',
      'reports.read_own',
    ],
  },
  {
    key: 'sales',
    displayNameAr: 'مبيعات',
    displayNameEn: 'Sales',
    description: 'Manage leads and client conversions',
    permissionKeys: [
      'employees.read_basic',
      'attendance.read_own',
      'crm_leads.manage',
      'clients.read',
      'quotations_invoices.manage',
      'expenses.submit',
    ],
  },
  {
    key: 'freelancer',
    displayNameAr: 'مستقل',
    displayNameEn: 'Freelancer',
    description: 'Limited access to assigned projects and tasks',
    permissionKeys: [
      'attendance.read_own',
      'projects.read_assigned',
      'tasks.read_assigned',
      'asset_library.read_assigned',
      'expenses.submit',
    ],
  },
  {
    key: 'client',
    displayNameAr: 'عميل',
    displayNameEn: 'Client',
    description: 'External client portal access',
    permissionKeys: [
      'clients.read_self',
      'projects.read_own',
      'content_calendar.read_own',
      'quotations_invoices.read_own',
    ],
  },
]
